"""
Roleplay actions are defined here as a dictionary

Each key will be used to generate the roleplay command for that action.

Properties:
    help (str): The docstring added each action command method. This is what's displayed
    in Help by bot.
    aliases (list[str]): Aliases for the command name.
    description (str): The Embed description. Describing the roleplay action in present
    tense. Be sure to use {author} and {target} tags here as well.
    footer (str): Optional footer text to include in Embed. Useful for crediting members
    who came up with the idea.
    spoiler (bool): Use for lewd images. This will spoiler the image instead of openly
    displaying it in an Embed
    images must be a list of URLs. Even if there's only one image, define it as a list.
    consent_required (bool): If this key is True then the command will query the
    targeted member for their consent before sending the final Embed message
    consent_message (str): The consent message to present to the targeted member.
    Be sure to include {author} and {target} tags. If consent is not required for the
    action, this can just have None as a value.
    consent_owner (str): The consent message to present to the owner of the targeted
    member. Be sure to include {owner}, {author}, and {target} tags.
    deny_roles (list[int]): List of role IDs. if the target member has one of these
    roles the action cannot be performed on them.
    deny_message (str): Message to send if the action as denied.
    Be sure to include {author} and {target} tags.
"""

from . import const


ACTIONS = {
    "hug": {
        "help": "Hug a user!",
        "aliases": ["hugs"],
        "description": "{author} is hugging {target}.",
        "images": [
            "https://cdn.weeb.sh/images/rJaog0FtZ.gif",
            "https://cdn.weeb.sh/images/Hyv6uOQPZ.gif",
            "https://cdn.weeb.sh/images/BJx2l0ttW.gif",
            "https://media.giphy.com/media/wnsgren9NtITS/giphy.gif",
            "https://media.giphy.com/media/svXXBgduBsJ1u/giphy.gif",
            "https://media.giphy.com/media/3ZnBrkqoaI2hq/giphy.gif",
            "https://media.giphy.com/media/3o6ZsTopjMRVkJXAWI/giphy.gif",
            "https://media.giphy.com/media/od5H3PmEG5EVq/giphy.gif",
            "https://media.giphy.com/media/vVA8U5NnXpMXK/giphy.gif",
            "https://media.giphy.com/media/ZQN9jsRWp1M76/giphy.gif",
            "https://media.giphy.com/media/DjczAlIcyK1Co/giphy.gif",
            "https://media.giphy.com/media/C4gbG94zAjyYE/giphy.gif",
            "https://i.imgur.com/hM1LcZf.gif",
            "https://i.imgur.com/cRfX87T.gif",
            "https://cdn.weeb.sh/images/HyNJIaVCb.gif",
            "https://cdn.weeb.sh/images/ryMqdOXvZ.gif",
            "https://cdn.weeb.sh/images/Hk4qu_XvZ.gif",
            "https://cdn.weeb.sh/images/ByuHsvu8z.gif",
            "https://cdn.weeb.sh/images/Hy4hxRKtW.gif",
            "https://cdn.weeb.sh/images/Sk2gmRZZG.gif",
            "https://cdn.weeb.sh/images/HkfgF_QvW.gif",
            "https://cdn.weeb.sh/images/HJTWcTNCZ.gif",
            "https://cdn.weeb.sh/images/rko9O_mwW.gif",
            "https://cdn.weeb.sh/images/rkx1dJ25z.gif",
            "https://cdn.weeb.sh/images/BkZngAYtb.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to hug you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to hug {target}. Do you give consent?",
    },
    "cuddle": {
        "help": "Cuddle a user!",
        "aliases": ["cuddles", "cuddlewith"],
        "description": "{author} is cuddling with {target}.",
        "images": [
            "https://cdn.weeb.sh/images/BkTe8U7v-.gif",
            "https://cdn.weeb.sh/images/SykzL87D-.gif",
            "https://cdn.weeb.sh/images/BywGX8caZ.gif",
            "https://cdn.weeb.sh/images/SJceIU7wZ.gif",
            "https://cdn.weeb.sh/images/SJn18IXP-.gif",
            "https://cdn.weeb.sh/images/B1Qb88XvW.gif",
            "https://cdn.weeb.sh/images/r1XEOymib.gif",
            "https://cdn.weeb.sh/images/SJLkLImPb.gif",
            "https://cdn.weeb.sh/images/SyUYOJ7iZ.gif",
            "https://cdn.weeb.sh/images/rkBl8LmDZ.gif",
            "https://cdn.weeb.sh/images/B1S1I87vZ.gif",
            "https://cdn.weeb.sh/images/r1s9RqB7G.gif",
            "https://cdn.weeb.sh/images/Hy5y88mPb.gif",
            "https://cdn.weeb.sh/images/rkA6SU7w-.gif",
            "https://cdn.weeb.sh/images/r1A77CZbz.gif",
            "https://cdn.weeb.sh/images/SJYxIUmD-.gif",
            "https://cdn.weeb.sh/images/H1SfI8XwW.gif",
            "https://cdn.weeb.sh/images/rJCAH8XPb.gif",
            "https://cdn.weeb.sh/images/By03IkXsZ.gif",
            "https://cdn.weeb.sh/images/ryfyLL7D-.gif",
            "https://cdn.weeb.sh/images/BJwpw_XLM.gif",
            "https://cdn.weeb.sh/images/r1VzDkmjW.gif",
            "https://cdn.weeb.sh/images/HkzArUmvZ.gif",
            "https://cdn.weeb.sh/images/r1A77CZbz.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to cuddle with you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} cuddle with {target}. Do you give consent?",
    },
    "kiss": {
        "help": "Kiss a user!",
        "aliases": ["kisses", "smooch"],
        "description": "{author} is kissing {target}.",
        "images": [
            "https://cdn.weeb.sh/images/r1cB3aOwW.gif",
            "https://i.imgur.com/UxZqNBV.gif",
            "https://cdn.weeb.sh/images/Hy-oQl91z.gif",
            "https://cdn.weeb.sh/images/rJ6PWohA-.gif",
            "https://cdn.weeb.sh/images/rJrCj6_w-.gif",
            "https://i.imgur.com/0diWDja.gif",
            "https://i.imgur.com/84qXbQT.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to kiss you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to kiss {target}. Do you give consent?",
    },
    "slap": {
        "help": "Slap a user!",
        "aliases": ["slaps"],
        "description": "{author} is slapping {target}.",
        "images": [
            "https://cdn.weeb.sh/images/H16aQJFvb.gif",
            "https://media1.tenor.com/images/d14969a21a96ec46f61770c50fccf24f/tenor.gif?itemid=5509136",
            "https://media1.tenor.com/images/9ea4fb41d066737c0e3f2d626c13f230/tenor.gif?itemid=7355956",
            "https://media1.tenor.com/images/4a6b15b8d111255c77da57c735c79b44/tenor.gif?itemid=10937039",
            "https://media1.tenor.com/images/153b2f1bfd3c595c920ce60f1553c5f7/tenor.gif?itemid=10936993",
            "https://media1.tenor.com/images/4fa82be21ffd18c99a9708ba209d56ad/tenor.gif?itemid=5318916",
            "https://media1.tenor.com/images/1ba1ea1786f0b03912b1c9138dac707c/tenor.gif?itemid=5738394",
            "https://i.imgur.com/EO8udG1.gif",
            "https://i.imgur.com/lMmn1wy.gif",
            "https://i.imgur.com/TuSUTg5.gif",
            "https://i.imgur.com/9Ql97mO.gif",
            "https://i.imgur.com/VBGqeIU.gif",
            "https://i.imgur.com/uPZwGFQ.gif",
            "https://i.imgur.com/eNiOIMB.gif",
            "https://i.imgur.com/gsAGyoI.gif",
            "https://cdn.weeb.sh/images/HyPjmytDW.gif",
            "https://cdn.weeb.sh/images/BJ8o71tD-.gif",
            "https://cdn.weeb.sh/images/BJLCX1Kw-.gif",
            "https://cdn.weeb.sh/images/rJvR71KPb.gif",
            "https://cdn.weeb.sh/images/SkZTQkKPZ.gif",
            "https://cdn.weeb.sh/images/Hkw1VkYP-.gif",
            "https://cdn.weeb.sh/images/BkxEo7ytDb.gif",
            "https://cdn.weeb.sh/images/B1fnQyKDW.gif",
            "https://cdn.weeb.sh/images/Bkj-oaV0Z.gif",
            "https://cdn.weeb.sh/images/r1siXJKw-.gif",
            "https://cdn.weeb.sh/images/r1VF-lcyz.gif",
            "https://cdn.weeb.sh/images/BJgsX1Kv-.gif",
            "https://cdn.weeb.sh/images/SkKn-xc1f.gif",
            "https://cdn.weeb.sh/images/Sk9mfCtY-.gif",
            "https://cdn.weeb.sh/images/ry_RQkYDb.gif",
            "https://cdn.weeb.sh/images/HkK2mkYPZ.gif",
            "https://cdn.weeb.sh/images/S1ylxxc1M.gif",
            "https://cdn.weeb.sh/images/SJdXoVguf.gif",
            "https://cdn.weeb.sh/images/ByHUMRNR-.gif",
            "https://cdn.weeb.sh/images/SkdyfWCSf.gif",
            "https://cdn.weeb.sh/images/rknn7Jtv-.gif",
            "https://cdn.weeb.sh/images/rJgTQ1tvb.gif",
            "https://cdn.weeb.sh/images/rkaqm1twZ.gif",
            "https://cdn.weeb.sh/images/ryn_Zg5JG.gif",
            "https://cdn.weeb.sh/images/SJ-CQytvW.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to slap you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to slap {target}. Do you give consent?",
    },
    "lick": {
        "help": "Lick a user!",
        "aliases": ["licks"],
        "description": "{author} is licking {target}.",
        "images": [
            "https://media1.tenor.com/images/c4f68fbbec3c96193386e5fcc5429b89/tenor.gif?itemid=13451325",
            "https://media1.tenor.com/images/ec2ca0bf12d7b1a30fea702b59e5a7fa/tenor.gif?itemid=13417195",
            "https://cdn.weeb.sh/images/HkEqiExdf.gif",
            "https://media1.tenor.com/images/6b701503b0e5ea725b0b3fdf6824d390/tenor.gif?itemid=12141727",
            "https://media1.tenor.com/images/069076cc8054bb8b114c5a37eec70a1f/tenor.gif?itemid=13248504",
            "https://media1.tenor.com/images/fc0ef2ba03d82af0cbd6c5815c3c83d5/tenor.gif?itemid=12141725",
            "https://media1.tenor.com/images/efd46743771a78e493e66b5d26cd2af1/tenor.gif?itemid=14002773",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to lick you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to lick {target}. Do you give consent?",
    },
    "highfive": {
        "help": "High five a user!",
        "aliases": ["highfives", "high5"],
        "description": "{author} gave {target} a high five.",
        "images": [
            "https://media1.tenor.com/images/0ae4995e4eb27e427454526c05b2e3dd/tenor.gif?itemid=12376992",
            "https://media1.tenor.com/images/7b1f06eac73c36721912edcaacddf666/tenor.gif?itemid=10559431",
            "https://media1.tenor.com/images/c3263b8196afc25ddc1d53a4224347cd/tenor.gif?itemid=9443275",
            "https://media1.tenor.com/images/56d6725009312574e4798c732cebc5fe/tenor.gif?itemid=12312526",
            "https://media1.tenor.com/images/e96d2396570a2fadd9c83e284a1ca675/tenor.gif?itemid=5390726",
            "https://media1.tenor.com/images/106c8e64e864230341b59cc892b5a980/tenor.gif?itemid=5682921",
            "https://media1.tenor.com/images/b714d7680f8b49d69b07bc2f1e052e72/tenor.gif?itemid=13400356",
            "https://media1.tenor.com/images/0c23b320822afd5b1ce3faf01c2b9b69/tenor.gif?itemid=14137078",
            "https://media1.tenor.com/images/e2f299d05a7b1832314ec7a331440d4e/tenor.gif?itemid=5374033",
            "https://media1.tenor.com/images/16267f3a34efb42598bd822effaccd11/tenor.gif?itemid=14137081",
            "https://media1.tenor.com/images/9730876547cb3939388cf79b8a641da9/tenor.gif?itemid=8073516",
            "https://media1.tenor.com/images/ce85a2843f52309b85515f56a0a49d06/tenor.gif?itemid=14137077",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to give you a high five, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to high five {target}. Do you give consent?",
    },
    "feed": {
        "help": "Feed a user!",
        "aliases": ["feeds"],
        "description": "{author} feeds {target}.",
        "images": [
            "https://media1.tenor.com/images/93c4833dbcfd5be9401afbda220066ee/tenor.gif?itemid=11223742",
            "https://media1.tenor.com/images/33cfd292d4ef5e2dc533ff73a102c2e6/tenor.gif?itemid=12165913",
            "https://media1.tenor.com/images/72268391ffde3cd976a456ee2a033f46/tenor.gif?itemid=7589062",
            "https://media1.tenor.com/images/4b48975ec500f8326c5db6b178a91a3a/tenor.gif?itemid=12593977",
            "https://media1.tenor.com/images/187ff5bc3a5628b6906935232898c200/tenor.gif?itemid=9340097",
            "https://media1.tenor.com/images/15e7d9e1eb0aad2852fabda1210aee95/tenor.gif?itemid=12005286",
            "https://media1.tenor.com/images/d08d0825019c321f21293c35df8ed6a9/tenor.gif?itemid=9032297",
            "https://media1.tenor.com/images/571da4da1ad526afe744423f7581a452/tenor.gif?itemid=11658244",
            "https://media1.tenor.com/images/6bde17caa5743a22686e5f7b6e3e23b4/tenor.gif?itemid=13726430",
            "https://media1.tenor.com/images/fd3616d34ade61e1ac5cd0975c25a917/tenor.gif?itemid=13653906",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to feed you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to feed {target}. Do you give consent?",
    },
    "tickle": {
        "help": "Tickle a user!",
        "aliases": ["tickles"],
        "description": "{author} is tickling {target}.",
        "images": [
            "https://media1.tenor.com/images/02f62186ccb7fa8a2667f3216cfd7e13/tenor.gif?itemid=13269751",
            "https://media1.tenor.com/images/d38554c6e23b86c81f8d4a3764b38912/tenor.gif?itemid=11379131",
            "https://media1.tenor.com/images/05a64a05e5501be2b1a5a734998ad2b2/tenor.gif?itemid=11379130",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to tickle you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to tickle {target}. Do you give consent?",
    },
    "poke": {
        "help": "Poke a user!",
        "aliases": ["pokes"],
        "description": "{author} is poking {target}.",
        "images": [
            "https://media1.tenor.com/images/3b2bfd09965bd77f2a8cb9ba59cedbe4/tenor.gif?itemid=5607667",
            "https://media1.tenor.com/images/514efe749cb611eb382713596e3427d8/tenor.gif?itemid=13054528",
            "https://media1.tenor.com/images/8795ff617de989265907eed8029a99a3/tenor.gif?itemid=14629871",
            "https://media1.tenor.com/images/1e0ea8b241a7db2b9c03775133138733/tenor.gif?itemid=10064326",
            "https://media1.tenor.com/images/90f68d48795c51222c60afc7239c930c/tenor.gif?itemid=8701034",
            "https://media1.tenor.com/images/01b264dc057eff2d0ee6869e9ed514c1/tenor.gif?itemid=14346763",
            "https://media1.tenor.com/images/f8a48a25f47d5d12342705c7c87368bb/tenor.gif?itemid=14134415",
            "https://media.tenor.com/images/6b5c1554a6ee9d48ab0392603bab8a8e/tenor.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to poke you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to poke {target}. Do you give consent?",
    },
    "smug": {
        "description": "{author} is acting smug towards {target}.",
        "images": [
            "https://i.kym-cdn.com/photos/images/original/001/087/562/93c.gif",
            "https://i.kym-cdn.com/photos/images/newsfeed/001/161/167/eda.gif",
            "https://media1.tenor.com/images/d9b3127da3f9419cbb28f9f7c00860d8/tenor.gif?itemid=9588226",
            "https://media1.tenor.com/images/0097fa7f957477f9edc5ff147bb9a5ad/tenor.gif?itemid=12390496",
        ],
        "consent_required": False,
        "consent_message": None,
    },
    "holdhands": {
        "help": "Hold hands with a user!",
        "description": "{author} is holding {target}'s hand",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/4SasCu2.gif",
            "https://panel.unicornia.net/botimages/biFPihV.gif",
            "https://panel.unicornia.net/botimages/lnVGxdN.gif",
            "https://panel.unicornia.net/botimages/DfDKZGT.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to hold your hand, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to hold {target}'s hand. Do you give consent?",
    },
    "suck": {
        "help": "Suck a user!",
        "aliases": ["sucks", "bj", "blowjob"],
        "description": "{author} is sucking {target}.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/NvGFyQJ.gif",
            "https://panel.unicornia.net/botimages/LJa2Nag.gif",
            "https://panel.unicornia.net/botimages/xXJePAv.gif",
            "https://panel.unicornia.net/botimages/94HNIeK.gif",
            "https://panel.unicornia.net/botimages/grUtryW.gif",
            "https://panel.unicornia.net/botimages/OS3qkyz.gif",
            "https://panel.unicornia.net/botimages/gEjjKJh.gif",
            "https://panel.unicornia.net/botimages/PAKjLsk.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to suck you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to suck {target}. Do you give consent?",
        "deny_roles": [const.LOCKED, const.HONORARY_CHASTITY],
        "deny_message": "{author} can't suck {target} in their current state.",
    },
    "cunnilingus": {
        "description": "{author} is eating out {target}.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/cunnilingus1.gif",
            "https://panel.unicornia.net/botimages/cunnilingus2.gif",
            "https://panel.unicornia.net/botimages/cunnilingus3.gif",
            "https://panel.unicornia.net/botimages/cunnilingus4.gif",
            "https://panel.unicornia.net/botimages/cunnilingus5.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to eat you out, {target}. Do you give consent?",
    },
    "spank": {
        "help": "Spank a user!",
        "aliases": ["spanks"],
        "description": "{author} is spanking {target}.",
        "images": [
            "https://panel.unicornia.net/botimages/",
            "https://panel.unicornia.net/botimages/rikka-takanashi-bad-girl.gif",
            "https://panel.unicornia.net/botimages/h8PWgcl.gif",
            "https://panel.unicornia.net/botimages/YTSIU80.gif",
            "https://panel.unicornia.net/botimages/dG7qAye.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to spank you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to spank {target}. Do you give consent?",
    },
    "grope": {
        "help": "Grope a user!",
        "aliases": ["gropes", "fondle", "fondles"],
        "description": "{author} is groping {target}.",
        "images": [
            "https://panel.unicornia.net/botimages/gJYOuPo.gif",
            "https://panel.unicornia.net/botimages/pFX9XEJ.gif",
            "https://panel.unicornia.net/botimages/em3tgS0.gif",
            "https://panel.unicornia.net/botimages/ZgOXZ8a.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to grope you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to grope {target}. Do you give consent?",
    },
    "fuck": {
        "help": "Fuck a user!",
        "aliases": ["fucks", "bang", "bangs", "havesexwith"],
        "description": "{author} is fucking {target}.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/rTYPXyF.gif",
            "https://panel.unicornia.net/botimages/msZye91.gif",
            "https://panel.unicornia.net/botimages/CDbagGK.gif",
            "https://panel.unicornia.net/botimages/wzIgSWc.gif",
            "https://panel.unicornia.net/botimages/6v82Fu6.gif",
            "https://panel.unicornia.net/botimages/9ycCb8R.gif",
            "https://panel.unicornia.net/botimages/8a9bKlN.gif",
            "https://panel.unicornia.net/botimages/q7UTkdt.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to fuck you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to fuck {target}. Do you give consent?",
        "deny_roles": [const.LOCKED, const.HONORARY_CHASTITY],
        "deny_message": "{author} can't fuck {target} their current state.",
    },
    "caress": {
        "help": "Caress a user!",
        "aliases": ["caresses"],
        "description": "{author} is caressing {target}.",
        "footer": "Made with the help of neviyn",
        "images": [
            "https://panel.unicornia.net/botimages/CADWD1g.gif",
            "https://panel.unicornia.net/botimages/MeoHfps.gif",
            "https://panel.unicornia.net/botimages/3kUMbfI.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to caress you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to caress {target}. Do you give consent?",
    },
    "bow": {
        "help": "Bow to a user.",
        "aliases": ["bows", "bowto"],
        "description": "{author} is bowing to {target}.",
        "images": [
            "https://panel.unicornia.net/botimages/C5BVTfW.gif",
            "https://panel.unicornia.net/botimages/F9EDWhy.gif",
            "https://panel.unicornia.net/botimages/B32NP3T.gif",
            "https://panel.unicornia.net/botimages/avDRwRQ.gif",
        ],
        "consent_required": False,
        "consent_message": None,
    },
    "siton": {
        "help": "Sit on a user's face.",
        "aliases": ["sitson", "sitonface", "sitsonface"],
        "description": "{author} is sitting on {target}'s face.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/dIkTN8t.gif",
            "https://panel.unicornia.net/botimages/60SNbrc.gif",
            "https://panel.unicornia.net/botimages/LS3hMtD.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to sit on your face, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to sit on {target}'s face. Do you give consent?",
    },
    "ride": {
        "help": "Ride a user",
        "aliases": ["rides"],
        "description": "{author} is riding {target}.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/08AAAL2.gif",
            "https://panel.unicornia.net/botimages/79DwpjO.gif",
            "https://panel.unicornia.net/botimages/WFLLdh6.gif",
            "https://panel.unicornia.net/botimages/lUSZZD5.gif",
            "https://panel.unicornia.net/botimages/W1Bd2v2.gif",
            "https://panel.unicornia.net/botimages/YRCRMAq.gif",
            "https://panel.unicornia.net/botimages/7AIJavl.gif",
            "https://panel.unicornia.net/botimages/UlPdyXb.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to ride you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to ride {target}. Do you give consent?",
        "deny_roles": [const.LOCKED, const.HONORARY_CHASTITY],
        "deny_message": "{author} can't ride {target} in their current state.",
    },
    "peg": {
        "help": "Peg a user!",
        "aliases": ["pegs", "strapon"],
        "description": "{author} is pegging {target}.",
        "spoiler": True,
        "images": [
            "https://panel.unicornia.net/botimages/evzDCB0.gif",
            "https://panel.unicornia.net/botimages/XwqUI8f.gif",
            "https://panel.unicornia.net/botimages/pUO7vkd.gif",
            "https://panel.unicornia.net/botimages/8a9bKlN.gif",
            "https://panel.unicornia.net/botimages/q7UTkdt.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to peg you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to peg {target}. Do you give consent?",
    },
    "bite": {
        "help": "Bite a user!",
        "aliases": ["bites"],
        "description": "{author} is biting {target}.",
        "images": [
            "https://panel.unicornia.net/botimages/bite4.gif",
            "https://panel.unicornia.net/botimages/anime-bite2.gif",
            "https://panel.unicornia.net/botimages/anime-bite.gif",
            "https://panel.unicornia.net/botimages/bite.gif",
            "https://panel.unicornia.net/botimages/bite3.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to bite you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to bite {target}. Do you give consent?",
    },
    "uppies": {
        "help": "Get uppies from a user!",
        "description": "{author} is given uppies by {target}.",
        "images": [
            "https://i.imgur.com/lyZe3UT.gif",
            "https://i.imgur.com/gnaCOmx.gif",
            "https://i.imgur.com/BEQFIFO.gif",
            "https://i.imgur.com/Y3sUFwE.gif",
            "https://i.imgur.com/poW3tpq.gif",
            "https://i.imgur.com/T6S7BcP.gif",
            "https://i.imgur.com/z02YFRd.gif",
            "https://i.imgur.com/zL8NPh2.gif",
            "https://i.imgur.com/8jwiwYU.gif",
            "https://i.imgur.com/E8PTtWf.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants uppies from {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants uppies from {target}. Do you give consent?",
        "footer": "Requested by Radon",
    },
    "tuckin": {
        "help": "Tuck in a user",
        "aliases": ["tucksin"],
        "description": "{author} has tucked in {target}.",
        "images": [
            "https://panel.unicornia.net/botimages/tuckin1.gif",
            "https://panel.unicornia.net/botimages/tuckin2.gif",
            "https://panel.unicornia.net/botimages/tuckin3.gif",
            "https://panel.unicornia.net/botimages/tuckin4.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to tuck you in, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to tuck in {target}. Do you give consent?",
    },
    "pat": {
        "help": "Pat a user!",
        "aliases": ["pats"],
        "description": "{author} is patting {target}.",
        "images": [
            "https://cdn.weeb.sh/images/r180y1Yvb.gif",
            "http://i.imgur.com/10VrpFZ.gif",
            "http://i.imgur.com/x0u35IU.gif",
            "http://i.imgur.com/0gTbTNR.gif",
            "http://i.imgur.com/hlLCiAt.gif",
            "http://i.imgur.com/sAANBDj.gif",
            "https://i.imgur.com/10VrpFZ.gif" "https://i.imgur.com/x0u35IU.gif",
            "https://i.imgur.com/sAANBDj.gif",
            "https://i.imgur.com/wtxwpm1.gif",
            "https://i.imgur.com/3eR7weH.gif",
            "https://i.imgur.com/cK8Ro3x.gif",
            "https://i.imgur.com/qtHlt3n.gif",
            "https://i.imgur.com/bzzodCZ.gif",
            "https://cdn.weeb.sh/images/r180y1Yvb.gif",
            "https://cdn.weeb.sh/images/Sky1x1YwW.gif",
            "https://cdn.weeb.sh/images/r1Y5L6NCZ.gif",
            "https://cdn.weeb.sh/images/HJGQlJYwb.gif",
            "https://cdn.weeb.sh/images/rkBZkRttW.gif",
            "https://cdn.weeb.sh/images/rJavp1KVM.gif",
            "https://cdn.weeb.sh/images/r1AsJ1twZ.gif",
            "https://cdn.weeb.sh/images/ry1tlj2AW.gif",
            "https://cdn.weeb.sh/images/HyqTkyFvb.gif",
            "https://cdn.weeb.sh/images/H1jnJktPb.gif",
            "https://cdn.weeb.sh/images/ryLKqTVCW.gif",
            "https://cdn.weeb.sh/images/rJJXgJFDW.gif",
            "https://i.imgur.com/grAHcaB.gif",
            "https://cdn.weeb.sh/images/SJS1lyYwW.gif",
            "https://cdn.weeb.sh/images/rkbblkYvb.gif",
            "https://cdn.weeb.sh/images/H1s5hx0Bf.gif",
            "https://cdn.weeb.sh/images/rkSN7g91M.gif",
            "https://cdn.weeb.sh/images/rktsca40-.gif",
            "https://cdn.weeb.sh/images/ryh6x04Rb.gif",
            "https://cdn.weeb.sh/images/rkTC896_f.gif",
            "https://cdn.weeb.sh/images/SJudB96_f.gif",
            "https://cdn.weeb.sh/images/SJudB96_f.gif",
            "https://cdn.weeb.sh/images/r1lVQgcyG.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to pat you, {target} Do you give consent?",
        "consent_owner": "{owner}, {author} wants to pat {target}. Do you give consent?",
    },
    "pet": {
        "help": "Pet a user!",
        "aliases": ["pets"],
        "description": "{author} pets {target}.",
        "images": [
            "https://i.imgur.com/JEc9ojf.gif",
            "https://i.imgur.com/DblQfCO.gif",
            "https://i.imgur.com/myHZY4L.gif",
            "https://i.imgur.com/UPfLjsO.gif",
            "https://i.imgur.com/R1kAo6g.gif",
            "https://i.imgur.com/2viEd5X.gif",
        ],
        "consent_required": True,
        "consent_message": "{author} wants to pet you, {target}. Do you give consent?",
        "consent_owner": "{owner}, {author} wants to pet {target}. Do you give consent?",
    },
}
