import logging
import os

LOGGER_LEVEL = logging.DEBUG

# LOVENSE_DEVELOPER_TOKEN = os.getenv("LOVENSE_DEVELOPER_TOKEN")
LOVENSE_DEVELOPER_TOKEN = "DlAhKO58i05za5w0-Tx7a0COowJ6A-1zL0NED__sBhc9FipZyUCG2P2_FxInTDTYOYqcZL9SbhLs049q68aAZA"
WEBSERVER_PORT = 8000
